name: CI

on:
  push:
    branches: [ main, "releases/**" ]
  pull_request:
    branches: [ main, "releases/**" ]

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest-l

    permissions:
      contents: read
      packages: read

    steps:
      - uses: actions/checkout@v4
        with:
          # We need to fetch the parent branch information for SonarCloud
          fetch-depth: 0

      - name: Read Node Version
        run: echo "NODE_VERSION=$(jq -crM .engines.node < package.json)" >> $GITHUB_OUTPUT
        shell: bash
        id: node_version

      - name: Use Node.js ${{ steps.node_version.outputs.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: '${{ steps.node_version.outputs.NODE_VERSION }}'
          cache: 'npm'

      - name: Setup NPM Auth for GitHub Package Registry
        run: echo '//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}' >> ~/.npmrc

      - name: Run Lint
        run: make do-lint
        env:
          # Needed to fetch packages from GitHub Package Registry
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Services
        run: |
          ./utils/enable-postgres-backend | grep '^export ' | sed 's/^export //g' >> $GITHUB_ENV
          ./utils/enable-redis-backend | grep '^export ' | sed 's/^export //g' >> $GITHUB_ENV
          ./utils/enable-firestore-backend | grep '^export ' | sed 's/^export //g' >> $GITHUB_ENV

      - name: Run Tests
        run: make test
        env:
          # Needed to fetch packages from GitHub Package Registry
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save PR Number for SonarCloud
        if: github.event_name == 'pull_request'
        run: |
          rm -f .pr
          echo '${{ github.event.number }}' > .pr

      # Save artifacts from testing for running SonarCloud in a privileged step
      - name: Save Tested Artifacts for SonarCloud
        if: success()
        uses: actions/upload-artifact@v6
        with:
          name: test-artifacts
          path: |
            .pr
            .coverage
            node_modules

      - name: Stop Services
        run: |
          ./utils/enable-postgres-backend off
          ./utils/enable-redis-backend off
          ./utils/enable-firestore-backend off
